[profile.default]
src = "."
test = "test"
out = "out"
libs = ["../lib"]
solc_version = "0.8.22"

# Required for OpenZeppelin Upgrades safety validations:
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=../lib/forge-std/src/"
]